[programs.localnet]
# this must exactly match the pubkey you saw printed above
nodefi_vault = "F14yVkHb8S1ByEStSshM1Bep6DkFpdA9yiUkgNcs9r1V"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
