# programs/nodefi_vault/Cargo.toml
[package]
name = "nodefi_vault"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
idl-build = ["anchor-lang/idl-build"]

[profile.release]
overflow-checks = true

[dependencies]
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
<<<<<<< HEAD
anchor-spl  = { version = "0.31.1", features = ["token"] }
=======
anchor-spl = { version = "0.31.1", features = ["token", "token_2022"] }

>>>>>>> 74b33a4 (refactor: Update dependencies and remove unused instruction file)
